apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-config
data:
  nginx.conf: |
    upstream loadbalance {
        least_conn;
        server nodejs:8080;
    }

    server {
        location / {
            proxy_pass http://loadbalance;
        }
    }