apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "my-nodejsApp.fullname" . }}-build
  labels:
    app: {{ include "my-nodejsApp.name" . }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: docker:{{ .Values.build.dockerTag }}
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
          command: ["sh", "-c"]
          args:
            - |
              docker login {{ .Values.build.registry }} -u {{ .Values.build.username }} -p {{ .Values.build.password }};
              docker build --build-arg NODE_ENV={{ .Values.appEnv }} -t {{ .Values.nodeJsImage.repository }}:{{ .Values.nodeJsImage.tag }} -f {{ .Values.build.contextPath }}/{{ .Values.build.dockerfileName }} {{ .Values.build.contextPath }};
              docker build --build-arg NODE_ENV={{ .Values.appEnv }} -t {{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }} -f {{ .Values.build.contextPath }}/{{ .Values.build.nginxDockerFileName }} {{ .Values.build.contextPath }};


